### ISSUE TITLE
Trezor T connection issues

### ISSUE THREAD

**Issue by rafx85** [RabbyHub/Rabby#1850]
When I try to connect Trezor T with Rabby I always got screen to install Trezor Bridge despite it is already installed. On Rainbow and Metamask connection working good, only Rabby has problems with that.

**Comment by vvvvvv1vvvvvv** [comment]
Can you make a screenshot?

**Comment by rafx85** [comment]
![image](https://github.com/RabbyHub/Rabby/assets/11873974/7fb4d92f-ca3e-4d79-b6a2-143e13c022c7)

Look like this.

**Comment by vvvvvv1vvvvvv** [comment]
Looks like you are using self-built Rabby? 
The Chrome extension id is wrong, did you change any code?

**Comment by rafx85** [comment]
No, it's just someone's image for metamask, but I have the same screen for Rabby.

**Comment by vvvvvv1vvvvvv** [comment]
@heisenberg-2077 any idea?

**Comment by 0x398** [comment]
I confirm the issue. Rabby do not prompt to connect Trezor via webhid (like it probably should), Trezor connect falls back to connection via the bridge, but bridge rejects the connection.

**Comment by vvvvvv1vvvvvv** [comment]
tbh Trezor connection page is provided by Trezor team so I can't make sure what's wrong with it, but did restart browser/computed works for you?

**Comment by vvvvvv1vvvvvv** [comment]
also, it works fine in my side

**Comment by rafx85** [comment]
> tbh Trezor connection page is provided by Trezor team so I can't make sure what's wrong with it, but did restart browser/computed works for you?

Does not work for me, other wallets work fine with Trezor, just Rabby got that issue, did you check on Trezor T or the Trezor One, maybe it's difference here?

**Comment by heisenberg-2077** [comment]
Please see if you can open http://127.0.0.1:21325, this is the address of the bridge service.
If it doesn't work, please install the bridge as required and restart your computer. 
@rafx85

**Comment by rafx85** [comment]
> Please see if you can open http://127.0.0.1:21325, this is the address of the bridge service. If it doesn't work, please install the bridge as required and restart your computer. @rafx85

Yes, it's working good.

**Comment by heisenberg-2077** [comment]
You mean the issue is solved?

**Comment by rafx85** [comment]
> You mean the issue is solved?

No issue still there, just the link is working. No need to restart computer or install bridge.

**Comment by heisenberg-2077** [comment]
Try upgrading the trezor firmware and reinstalling the latest version of bridge.

**Comment by rafx85** [comment]
> Try upgrading the trezor firmware and reinstalling the latest version of bridge.

There is no newer version of bridge or firmware, I have latest, problem must be with rabby, other wallets work good with trezor.

**Comment by rafx85** [comment]
> Try upgrading the trezor firmware and reinstalling the latest version of bridge.

Any progress here with adding trezor t support?

**Comment by emerylopes** [comment]
Hello @vvvvvv1vvvvvv !

I have just switched from Metamask to Rabby today.

When I try to add my Trezor T to Rabby using Chrome that supports WebUSB and get this screen:

![T](https://github.com/RabbyHub/Rabby/assets/69319870/57820265-aeb5-4dde-abb6-ffb94fdda20c)

I have no issues with Metamask:

![M](https://github.com/RabbyHub/Rabby/assets/69319870/c018b933-77a2-4edc-875d-08c20e0ebfd6)

Does Rabby supports WebUSB? Any plans to implement it?

**Comment by AJolly** [comment]
Theres also a big issue using wallets that have different trezor passphrases with rabby - you have to restart rabby every time when switching wallets.

**Comment by emerylopes** [comment]
@vvvvvv1vvvvvv thank you ! Everything is working fine on last update.
